// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Posto.Infrastructure.Context;

namespace Posto.Infrastructure.Migrations
{
    [DbContext(typeof(PostoContext))]
    [Migration("20190825044649_usuarioTable")]
    partial class usuarioTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Posto.ApplicationCore.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_EMPRESA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasMaxLength(200);

                    b.HasKey("IdEmpresa")
                        .HasName("ID_EMPRESA");

                    b.ToTable("EMPRESAS");
                });

            modelBuilder.Entity("Posto.ApplicationCore.Entities.Exemplo", b =>
                {
                    b.Property<int>("ExemploId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_EXEMPLO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasMaxLength(200);

                    b.HasKey("ExemploId")
                        .HasName("ID_EXEMPLO");

                    b.ToTable("EXEMPLOS");
                });

            modelBuilder.Entity("Posto.ApplicationCore.Entities.ExemploItem", b =>
                {
                    b.Property<int>("ExemploItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExemploId");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasMaxLength(200);

                    b.HasKey("ExemploItemId")
                        .HasName("ID");

                    b.HasIndex("ExemploId");

                    b.ToTable("EXEMPLOS_ITENS");
                });

            modelBuilder.Entity("Posto.ApplicationCore.Entities.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Cpf")
                        .HasMaxLength(30);

                    b.Property<string>("Nome")
                        .HasMaxLength(200);

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Posto.ApplicationCore.Entities.ExemploItem", b =>
                {
                    b.HasOne("Posto.ApplicationCore.Entities.Exemplo", "Exemplo")
                        .WithMany("Itens")
                        .HasForeignKey("ExemploId");
                });
#pragma warning restore 612, 618
        }
    }
}
